name: "Docker build"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  docker-build:
    name: Test docker build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2 # checkout the repo

      - uses: ljharb/actions/node/install@main
        name: "nvm install 20.15.1"
        with:
          node-version: 20.15.1
          skip-install: true
          skip-ls-check: true

      - name: Build docker image
        run: yarn docker:build
        env:
          BUILD_ID: ${{ github.run_number }}-${{ github.run_id }}
          NODE_ENV: production
          BUILD_SOURCE: aws
